version: '3'
services:
  postgres:
    container_name: dj_postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "SomeSecurePassword"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "0.5"
        reservations:
          memory: "1G"
          cpus: "0.5"
    networks:
      django:
        aliases:
          - postgres

networks:
  django: